package com.cybertek;

import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.concurrent.TimeUnit;

public class Xpath_Relative {

    public static void main(String[] args) {
        WebDriverManager.chromedriver().setup();
        WebDriver driver = new ChromeDriver();

        //https://the-internet.herokuapp.com/upload
        //                (By.xpath("//button[@class='btn btn-primary']")); // E[@A='t']

        driver.get("https://the-internet.herokuapp.com/frames\n");
        // make it slower for some sites, otherwise it fails to find element
        driver.manage().timeouts().implicitlyWait(1, TimeUnit.SECONDS);

        WebElement submit = driver.findElement

                // auto generated by an addon
                (By.xpath("//A[@href='/iframe'][text()='iFrame']/self::A")); // E[@A='t']
        submit.click();



    }
}